import { useState, useEffect } from 'react';
import type { FavoriteItem, RoutePlan, RouteRecommendation } from '../../types';
import ResultList from '../SearchTab/ResultList';
import { useLocale } from '../../context/LocaleContext';
import { useFavoritesContext } from '../../context/FavoritesContext';
import { Icon } from '../../icons';
import './FavoritesTab.css';

// ─────────────────────────────────────────────────────────────────────
// DEMO DATA — SEED_FAVORITES is sample display content only.
// It is used to pre-populate the favorites tab so the UI isn't empty
// on first visit.  Remove or replace with real user data when a
// backend persistence layer is added.
// ─────────────────────────────────────────────────────────────────────
const SEED_FAVORITES: RoutePlan[] = [
  {
    id: 'fav-001',
    total_price: 680,
    total_duration_minutes: 155,
    transfer_count: 0,
    score: 95,
    tag: '推荐',
    legs: [
      {
        transport_type: 'flight',
        from_city: '北京',
        from_city_en: 'Beijing',
        to_city: '上海',
        to_city_en: 'Shanghai',
        from_station: '首都机场T3',
        from_station_en: 'Capital Airport T3',
        to_station: '虹桥机场T2',
        to_station_en: 'Hongqiao Airport T2',
        departure_date: '2026-05-24',
        departure_time: '08:30',
        arrival_date: '2026-05-24',
        arrival_time: '11:05',
        duration_minutes: 155,
        price: 680,
        company: '中国国航',
        flight_train_no: 'CA1515',
      },
    ],
  },
  {
    id: 'fav-002',
    total_price: 520,
    total_duration_minutes: 145,
    transfer_count: 0,
    score: 92,
    legs: [
      {
        transport_type: 'flight',
        from_city: '上海',
        from_city_en: 'Shanghai',
        to_city: '广州',
        to_city_en: 'Guangzhou',
        from_station: '浦东机场T1',
        from_station_en: 'Pudong Airport T1',
        to_station: '白云机场T2',
        to_station_en: 'Baiyun Airport T2',
        departure_date: '2026-05-25',
        departure_time: '09:00',
        arrival_date: '2026-05-25',
        arrival_time: '11:25',
        duration_minutes: 145,
        price: 520,
        company: '南方航空',
        flight_train_no: 'CZ3504',
      },
    ],
  },
  {
    id: 'fav-003',
    total_price: 890,
    total_duration_minutes: 310,
    transfer_count: 1,
    score: 85,
    tag: '少换乘',
    legs: [
      {
        transport_type: 'flight',
        from_city: '北京',
        from_city_en: 'Beijing',
        to_city: '武汉',
        to_city_en: 'Wuhan',
        from_station: '大兴机场',
        from_station_en: 'Daxing Airport',
        to_station: '天河机场T3',
        to_station_en: 'Tianhe Airport T3',
        departure_date: '2026-05-26',
        departure_time: '07:15',
        arrival_date: '2026-05-26',
        arrival_time: '09:35',
        duration_minutes: 140,
        price: 480,
        company: '中国国航',
        flight_train_no: 'CA8203',
      },
      {
        transport_type: 'flight',
        from_city: '武汉',
        from_city_en: 'Wuhan',
        to_city: '深圳',
        to_city_en: 'Shenzhen',
        from_station: '天河机场T3',
        from_station_en: 'Tianhe Airport T3',
        to_station: '宝安机场T3',
        to_station_en: 'Bao\'an Airport T3',
        departure_date: '2026-05-26',
        departure_time: '11:00',
        arrival_date: '2026-05-26',
        arrival_time: '12:45',
        duration_minutes: 105,
        price: 410,
        company: '南方航空',
        flight_train_no: 'CZ8552',
      },
    ],
  },
  {
    id: 'fav-004',
    total_price: 620,
    total_duration_minutes: 180,
    transfer_count: 0,
    score: 91,
    legs: [
      {
        transport_type: 'flight',
        from_city: '成都',
        from_city_en: 'Chengdu',
        to_city: '杭州',
        to_city_en: 'Hangzhou',
        from_station: '天府机场T2',
        from_station_en: 'Tianfu Airport T2',
        to_station: '萧山机场T4',
        to_station_en: 'Xiaoshan Airport T4',
        departure_date: '2026-05-24',
        departure_time: '10:20',
        arrival_date: '2026-05-24',
        arrival_time: '13:20',
        duration_minutes: 180,
        price: 620,
        company: '四川航空',
        flight_train_no: '3U3865',
      },
    ],
  },
  {
    id: 'fav-005',
    total_price: 340,
    total_duration_minutes: 330,
    transfer_count: 0,
    score: 88,
    tag: '最便宜',
    legs: [
      {
        transport_type: 'train',
        from_city: '西安',
        from_city_en: 'Xi\'an',
        to_city: '南京',
        to_city_en: 'Nanjing',
        from_station: '西安北站',
        from_station_en: 'Xi\'an North Railway Station',
        to_station: '南京南站',
        to_station_en: 'Nanjing South Railway Station',
        departure_date: '2026-05-25',
        departure_time: '08:00',
        arrival_date: '2026-05-25',
        arrival_time: '13:30',
        duration_minutes: 330,
        price: 340,
        company: '中国铁路',
        flight_train_no: 'G1914',
      },
    ],
  },
  {
    id: 'fav-006',
    total_price: 450,
    total_duration_minutes: 120,
    transfer_count: 0,
    score: 94,
    tag: '最快',
    legs: [
      {
        transport_type: 'flight',
        from_city: '武汉',
        from_city_en: 'Wuhan',
        to_city: '重庆',
        to_city_en: 'Chongqing',
        from_station: '天河机场T3',
        from_station_en: 'Tianhe Airport T3',
        to_station: '江北机场T3',
        to_station_en: 'Jiangbei Airport T3',
        departure_date: '2026-05-26',
        departure_time: '14:00',
        arrival_date: '2026-05-26',
        arrival_time: '16:00',
        duration_minutes: 120,
        price: 450,
        company: '东方航空',
        flight_train_no: 'MU2456',
      },
    ],
  },
  {
    id: 'fav-007',
    total_price: 720,
    total_duration_minutes: 160,
    transfer_count: 0,
    score: 90,
    legs: [
      {
        transport_type: 'flight',
        from_city: '广州',
        from_city_en: 'Guangzhou',
        to_city: '北京',
        to_city_en: 'Beijing',
        from_station: '白云机场T2',
        from_station_en: 'Baiyun Airport T2',
        to_station: '首都机场T3',
        to_station_en: 'Capital Airport T3',
        departure_date: '2026-05-24',
        departure_time: '16:30',
        arrival_date: '2026-05-24',
        arrival_time: '19:10',
        duration_minutes: 160,
        price: 720,
        company: '海南航空',
        flight_train_no: 'HU7803',
      },
    ],
  },
  {
    id: 'fav-008',
    total_price: 580,
    total_duration_minutes: 150,
    transfer_count: 0,
    score: 89,
    legs: [
      {
        transport_type: 'flight',
        from_city: '深圳',
        from_city_en: 'Shenzhen',
        to_city: '上海',
        to_city_en: 'Shanghai',
        from_station: '宝安机场T3',
        from_station_en: 'Bao\'an Airport T3',
        to_station: '虹桥机场T2',
        to_station_en: 'Hongqiao Airport T2',
        departure_date: '2026-05-25',
        departure_time: '11:30',
        arrival_date: '2026-05-25',
        arrival_time: '14:00',
        duration_minutes: 150,
        price: 580,
        company: '春秋航空',
        flight_train_no: '9C8888',
      },
    ],
  },
  {
    id: 'fav-009',
    total_price: 410,
    total_duration_minutes: 420,
    transfer_count: 0,
    score: 86,
    legs: [
      {
        transport_type: 'train',
        from_city: '杭州',
        from_city_en: 'Hangzhou',
        to_city: '成都',
        to_city_en: 'Chengdu',
        from_station: '杭州东站',
        from_station_en: 'Hangzhou East Railway Station',
        to_station: '成都东站',
        to_station_en: 'Chengdu East Railway Station',
        departure_date: '2026-05-26',
        departure_time: '07:45',
        arrival_date: '2026-05-26',
        arrival_time: '14:45',
        duration_minutes: 420,
        price: 410,
        company: '中国铁路',
        flight_train_no: 'G2185',
      },
    ],
  },
  {
    id: 'fav-010',
    total_price: 660,
    total_duration_minutes: 140,
    transfer_count: 0,
    score: 93,
    legs: [
      {
        transport_type: 'flight',
        from_city: '南京',
        from_city_en: 'Nanjing',
        to_city: '西安',
        to_city_en: 'Xi\'an',
        from_station: '禄口机场T1',
        from_station_en: 'Lukou Airport T1',
        to_station: '咸阳机场T3',
        to_station_en: 'Xianyang Airport T3',
        departure_date: '2026-05-24',
        departure_time: '13:10',
        arrival_date: '2026-05-24',
        arrival_time: '15:30',
        duration_minutes: 140,
        price: 660,
        company: '东方航空',
        flight_train_no: 'MU2889',
      },
    ],
  },
  {
    id: 'fav-011',
    total_price: 380,
    total_duration_minutes: 110,
    transfer_count: 0,
    score: 87,
    legs: [
      {
        transport_type: 'flight',
        from_city: '重庆',
        from_city_en: 'Chongqing',
        to_city: '武汉',
        to_city_en: 'Wuhan',
        from_station: '江北机场T3',
        from_station_en: 'Jiangbei Airport T3',
        to_station: '天河机场T3',
        to_station_en: 'Tianhe Airport T3',
        departure_date: '2026-05-25',
        departure_time: '09:45',
        arrival_date: '2026-05-25',
        arrival_time: '11:35',
        duration_minutes: 110,
        price: 380,
        company: '厦门航空',
        flight_train_no: 'MF8467',
      },
    ],
  },
  {
    id: 'fav-012',
    total_price: 850,
    total_duration_minutes: 190,
    transfer_count: 0,
    score: 90,
    legs: [
      {
        transport_type: 'flight',
        from_city: '北京',
        from_city_en: 'Beijing',
        to_city: '成都',
        to_city_en: 'Chengdu',
        from_station: '大兴机场',
        from_station_en: 'Daxing Airport',
        to_station: '天府机场T2',
        to_station_en: 'Tianfu Airport T2',
        departure_date: '2026-05-26',
        departure_time: '12:00',
        arrival_date: '2026-05-26',
        arrival_time: '15:10',
        duration_minutes: 190,
        price: 850,
        company: '四川航空',
        flight_train_no: '3U3867',
      },
    ],
  },
  {
    id: 'fav-013',
    total_price: 490,
    total_duration_minutes: 155,
    transfer_count: 0,
    score: 88,
    legs: [
      {
        transport_type: 'flight',
        from_city: '上海',
        from_city_en: 'Shanghai',
        to_city: '深圳',
        to_city_en: 'Shenzhen',
        from_station: '浦东机场T2',
        from_station_en: '',
        to_station: '宝安机场T3',
        to_station_en: 'Bao\'an Airport T3',
        departure_date: '2026-05-24',
        departure_time: '15:00',
        arrival_date: '2026-05-24',
        arrival_time: '17:35',
        duration_minutes: 155,
        price: 490,
        company: '吉祥航空',
        flight_train_no: 'HO1155',
      },
    ],
  },
  {
    id: 'fav-014',
    total_price: 780,
    total_duration_minutes: 260,
    transfer_count: 1,
    score: 84,
    legs: [
      {
        transport_type: 'flight',
        from_city: '广州',
        from_city_en: 'Guangzhou',
        to_city: '长沙',
        to_city_en: 'Changsha',
        from_station: '白云机场T2',
        from_station_en: 'Baiyun Airport T2',
        to_station: '黄花机场T2',
        to_station_en: 'Huanghua Airport T2',
        departure_date: '2026-05-25',
        departure_time: '08:30',
        arrival_date: '2026-05-25',
        arrival_time: '10:00',
        duration_minutes: 90,
        price: 320,
        company: '南方航空',
        flight_train_no: 'CZ3388',
      },
      {
        transport_type: 'train',
        from_city: '长沙',
        from_city_en: 'Changsha',
        to_city: '杭州',
        to_city_en: 'Hangzhou',
        from_station: '长沙南站',
        from_station_en: 'Changsha South Railway Station',
        to_station: '杭州东站',
        to_station_en: 'Hangzhou East Railway Station',
        departure_date: '2026-05-25',
        departure_time: '11:00',
        arrival_date: '2026-05-25',
        arrival_time: '13:50',
        duration_minutes: 170,
        price: 460,
        company: '中国铁路',
        flight_train_no: 'G1362',
      },
    ],
  },
  {
    id: 'fav-015',
    total_price: 710,
    total_duration_minutes: 175,
    transfer_count: 0,
    score: 91,
    legs: [
      {
        transport_type: 'flight',
        from_city: '成都',
        from_city_en: 'Chengdu',
        to_city: '北京',
        to_city_en: 'Beijing',
        from_station: '双流机场T2',
        from_station_en: 'Shuangliu Airport T2',
        to_station: '首都机场T3',
        to_station_en: 'Capital Airport T3',
        departure_date: '2026-05-26',
        departure_time: '07:00',
        arrival_date: '2026-05-26',
        arrival_time: '09:55',
        duration_minutes: 175,
        price: 710,
        company: '中国国航',
        flight_train_no: 'CA4102',
      },
    ],
  },
  {
    id: 'fav-016',
    total_price: 290,
    total_duration_minutes: 300,
    transfer_count: 0,
    score: 85,
    tag: '最便宜',
    legs: [
      {
        transport_type: 'train',
        from_city: '西安',
        from_city_en: 'Xi\'an',
        to_city: '重庆',
        to_city_en: 'Chongqing',
        from_station: '西安北站',
        from_station_en: 'Xi\'an North Railway Station',
        to_station: '重庆北站',
        to_station_en: 'Chongqing North Railway Station',
        departure_date: '2026-05-24',
        departure_time: '09:20',
        arrival_date: '2026-05-24',
        arrival_time: '14:20',
        duration_minutes: 300,
        price: 290,
        company: '中国铁路',
        flight_train_no: 'D1979',
      },
    ],
  },
  {
    id: 'fav-017',
    total_price: 540,
    total_duration_minutes: 130,
    transfer_count: 0,
    score: 89,
    legs: [
      {
        transport_type: 'flight',
        from_city: '武汉',
        from_city_en: 'Wuhan',
        to_city: '南京',
        to_city_en: 'Nanjing',
        from_station: '天河机场T3',
        from_station_en: 'Tianhe Airport T3',
        to_station: '禄口机场T1',
        to_station_en: 'Lukou Airport T1',
        departure_date: '2026-05-25',
        departure_time: '10:45',
        arrival_date: '2026-05-25',
        arrival_time: '12:55',
        duration_minutes: 130,
        price: 540,
        company: '东方航空',
        flight_train_no: 'MU2548',
      },
    ],
  },
  {
    id: 'fav-018',
    total_price: 630,
    total_duration_minutes: 135,
    transfer_count: 0,
    score: 90,
    legs: [
      {
        transport_type: 'flight',
        from_city: '杭州',
        from_city_en: 'Hangzhou',
        to_city: '广州',
        to_city_en: 'Guangzhou',
        from_station: '萧山机场T4',
        from_station_en: 'Xiaoshan Airport T4',
        to_station: '白云机场T2',
        to_station_en: 'Baiyun Airport T2',
        departure_date: '2026-05-26',
        departure_time: '14:20',
        arrival_date: '2026-05-26',
        arrival_time: '16:35',
        duration_minutes: 135,
        price: 630,
        company: '长龙航空',
        flight_train_no: 'GJ8699',
      },
    ],
  },
  {
    id: 'fav-019',
    total_price: 220,
    total_duration_minutes: 95,
    transfer_count: 0,
    score: 92,
    tag: '最快',
    legs: [
      {
        transport_type: 'train',
        from_city: '南京',
        from_city_en: 'Nanjing',
        to_city: '上海',
        to_city_en: 'Shanghai',
        from_station: '南京南站',
        from_station_en: 'Nanjing South Railway Station',
        to_station: '上海虹桥站',
        to_station_en: 'Shanghai Hongqiao Railway Station',
        departure_date: '2026-05-24',
        departure_time: '18:00',
        arrival_date: '2026-05-24',
        arrival_time: '19:35',
        duration_minutes: 95,
        price: 220,
        company: '中国铁路',
        flight_train_no: 'G7021',
      },
    ],
  },
  {
    id: 'fav-020',
    total_price: 780,
    total_duration_minutes: 165,
    transfer_count: 0,
    score: 93,
    legs: [
      {
        transport_type: 'flight',
        from_city: '重庆',
        from_city_en: 'Chongqing',
        to_city: '北京',
        to_city_en: 'Beijing',
        from_station: '江北机场T3',
        from_station_en: 'Jiangbei Airport T3',
        to_station: '大兴机场',
        to_station_en: 'Daxing Airport',
        departure_date: '2026-05-25',
        departure_time: '11:00',
        arrival_date: '2026-05-25',
        arrival_time: '13:45',
        duration_minutes: 165,
        price: 780,
        company: '中国国航',
        flight_train_no: 'CA1439',
      },
    ],
  },
];

export default function FavoritesTab() {
  const { favorites } = useFavoritesContext();
  const { t } = useLocale();

  // Snapshot favorites on mount so unfavoriting a card doesn't immediately
  // remove it from view — the card stays until the user leaves and revisits
  // the tab (or refreshes the page).
  const [displayedFavorites, setDisplayedFavorites] = useState<FavoriteItem[]>(() => favorites);
  const displayedRecommendations = displayedFavorites.filter((item): item is RouteRecommendation => 'segments' in item);
  const displayedRoutes = displayedFavorites.filter((item): item is RoutePlan => 'legs' in item);

  useEffect(() => {
    // Re-sync on mount only — not on favorites change.
    setDisplayedFavorites(favorites);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="favorites">
      <div className="container">
        <h2 className="results-header">{t('favorites.title')}</h2>
        {displayedFavorites.length > 0 ? (
          <ResultList
            routes={displayedRoutes}
            recommendations={displayedRecommendations}
            loading={false}
            error=""
            searched={true}
            header={t('favorites.count', { count: String(displayedFavorites.length) })}
          />
        ) : (
          <div className="empty-state">
            <div className="empty-state__icon"><Icon name="status.heartEmpty" /></div>
            <div className="empty-state__title">{t('favorites.emptyTitle')}</div>
            <div className="empty-state__subtitle">{t('favorites.emptySubtitle')}</div>
          </div>
        )}
      </div>
    </div>
  );
}
